### ISSUE TITLE
Redirect Error When Sending Messages and Rendering Error When Scheduling Messages

### ISSUE THREAD

**Issue by Megamil** [douglara/woofed-crm#257]
I'm having trouble with sending and scheduling message delivery. Sometimes manual sending works, but sometimes it gives the error:

```
turbo.es2017-esm.js:3496 Error: Form responses must redirect to another location
    at t.value (turbo.es2017-esm.js:1034:21)
    at t.<anonymous> (turbo.es2017-esm.js:611:33)
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at p (turbo.es2017-esm.js:25:99)
    at a (turbo.es2017-esm.js:27:194)
    at turbo.es2017-esm.js:27:364
    at new Promise (<anonymous>)
    at t.<anonymous> (turbo.es2017-esm.js:27:97)
```

And this other error:

```
application.js:44 Uncaught TypeError: Cannot read properties of null (reading 'render')
    at application.js:44:39
    at turbo.es2017-esm.js:5427:40
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at p (turbo.es2017-esm.js:25:99)
    at a (turbo.es2017-esm.js:27:194)
    at turbo.es2017-esm.js:27:364
    at new Promise (<anonymous>)
    at turbo.es2017-esm.js:27:97
```

As for scheduling, it doesn't work for me, at least not if I close the screen.

**Comment by YukioArie** [comment]
Hey, are you using the updated development branch? Regarding the error `application.js:44 Uncaught TypeError: Cannot read properties of null (reading 'render')` , it's just an error in a JavaScript file that doesn't affect Woofed's functionalities. I'm investigating the error `turbo.es2017-esm.js:3496 Error: Form responses must redirect to another location` , but first, I need to know if you're using the updated development branch. Thanks for the report 😃

**Comment by douglara** [comment]
Close by inactivated
